---
version: 2.1

orbs:
  python: circleci/python@2.0.3
  taskfile: threecomma/taskfile@0.1.0

jobs:
  get_version:
    docker: &job_docker_conf
      - image: cimg/python:3.8
    steps: &install_fake_version
      - checkout
      - run: &create_fake_version_file
          # Running `setup.py` requires a `version` file, and the more or less
          # proper way to get that is to install avakas, though for testing this
          # feels better
          name: fake a version file
          command: "echo 'v0.0.0-testonlysofake.0' > version"
      - python/install-packages: &install_setup_py
          pkg-manager: "pip-dist"
      - run:
          name: Get correct version
          command: avakas show . --flavor git-native
      - persist_to_workspace:
          root: '.'
          paths:
            - version

  build:
    docker: *job_docker_conf
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - python/dist
      - persist_to_workspace:
          root: '.'
          paths:
            - dist

  test:
    # ToDo matrix
    docker: *job_docker_conf
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: &install_built_wheel
          name: install built wheel
          command: pip install dist/avakas-$(cat version)-py3-none-any.whl

      # install dev requirements for running tests
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: "requirements-dev.txt"
      - run:
          name: Run Tests
          command: make test

# ToDo, parameterize these, want to do it with some logic so a bool param gets
# me the --prerelease, but don't want to sink the time figuring that out quite
# yet -TMJ
  perchance_a_bump:
    docker: *job_docker_conf
    parameters:
      args:
        type: string
        default: ""

    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: *install_built_wheel
      - run:
          name: you can bump if you wanna
          command: avakas bump "." auto --dry-run --flavor git-native --default-bump patch --branch mainline << parameters.args >>


workflows:
  # Combining all three as:
  #   * there's not a situation where we want to not do any steps (the
  #     conditionals for maybe tag are in `maybe tag` step).
  #   * We can just share a persisted workspace among jobs. We _could_ do test
  #     and perchance_a_bump installing the package from setup.py or whatever,
  #     but I (Tyler) see no reason to do so -TMJ
  build_test_maybe_tag:
    jobs:
      - get_version
      - build
      - test
      - perchance_a_bump:
          filters:
            branches:
              ignore:
                - mainline
          args: "--prerelease --prerelease-prefix pre"
      - perchance_a_bump:
          filters:
            branches:
              only:
                - mainline
